#!/usr/bin/env python3

def myhex(bitstring):
    return hex(int(bitstring, 2))[2:].rjust(2, "0").upper()

data = [ [], [], [], [], [], [], [], [], [], [], [], [] ]
descriptions = []
with open("font.txt", "r") as f:
    for c in map(chr, range(0x20,0x5B)):
        descriptions.append(f.readline().strip()[1:])
        for row in range(10):
            rawbits = f.readline().strip()
            bits = "0b1" + rawbits[::-1]
            data[row].append(myhex(bits))
print("; Million Perfect Tiles Condensed pixel font")
print("; (c) 2022 by 4am")
print("; license:Open Font License 1.1, see OFL.txt")
print("; This file is automatically generated")
for row in range(10):
    print("CondensedRow%s" % row)
    for c, i in zip(data[row], range(len(data[row]))):
        print("         !byte $%s        ; %s" % (c, descriptions[i]))
